import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import "@/style/index.scss";
import { Header } from "@/components/header/Header";
import Fotter from "@/components/fotter/Fotter";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "NextJS tsx scss",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${roboto.className}`}>
        <Header />
        {children}
        <Fotter />
      </body>
    </html>
  );
}
